 [phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "npm install --legacy-peer-deps || npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

