# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:
  db-server:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ImmoSyncPro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - localdev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  boilerplate-api:
    entrypoint: ["./wait-for.sh", "postgres:5432", "-t", "120", "--", "dotnet", "Boilerplate.Api.dll"]
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile
    image: boilerplate-api:local
    container_name: boilerplate-api
    depends_on:
      - db-server
    networks:
      - localdev
    volumes:
      - ./etc/wait-for.sh:/app/wait-for.sh

volumes:
  postgres_data: